### ISSUE TITLE
rename orion variables

### ISSUE THREAD

**Issue by macfarla** [ConsenSys/web3js-quorum#22]
### Summary
in keys.js and wherever this is used. Orion deprecated in favour of tessera - but maybe we should just use "enclave" to be agnostic.
There are two `keys.js` file:
* `integration-tests/support/keys.js` used for integration tests
* `example/keys.js` used in the examples provided in web3js-quorum

### Acceptance tests
* Rename the orion varibale in the `keys.js` files to enclave (for example)
* Update the source code that uses that

**Comment by ricardolyn** [comment]
@achraf17 could you review this?
