### ISSUE TITLE
broken links from github pages to github 

### ISSUE THREAD

**Issue by macfarla** [ConsenSys/web3js-quorum#23]
From here https://consensys.github.io/web3js-quorum/latest/index.html there are a few broken links - I think because the `latest` tag doesn't exist in github
eg https://consensys.github.io/web3js-quorum/latest/index.html gives a 404

**Comment by nmvalera** [comment]
@macfarla 

https://consensys.github.io/web3js-quorum/latest/index.html seems to work.

Are there other links that are broken? Thank you

**Comment by achraf17** [comment]
@macfarla it seems to be working for me as well
Is there other links that are broken, please let us know
![image.png](https://images.zenhubusercontent.com/603cd205ddcfab510254faac/d49f0a76-868macd-4a47-a870-3d3c28f61628)

**Comment by macfarla** [comment]
This one is a 404 https://consensys.github.io/web3js-quorum/latest/7nodes-test and https://consensys.github.io/web3js-quorum/latest/CONTRIBUTING.md

**Comment by macfarla** [comment]
everything else seems fine
