### ISSUE TITLE
How to poll for missed events?

### ISSUE THREAD

**Issue by subhasisbanik** [ConsenSys/web3js-quorum#37]
I would like to explore the event feature of Quorum where I would be able to poll for emitted events.
I had a look at the https://consensys.github.io/web3js-quorum/latest/index.html
But I am unable to find any mention of how to handle events.
I had a look at https://web3js.readthedocs.io/en/v1.2.11/web3-eth-subscribe.html
But it did not work as expcected.

Please help.

**Comment by achraf17** [comment]
hi @subhasisbanik,
For event subscription, either for [blockchain emitted events](https://web3js.readthedocs.io/en/v1.5.2/web3-eth-subscribe.html) like ("pendingTransactions", "newBlockHeaders"...) or [contract emitted events](https://web3js.readthedocs.io/en/v1.5.2/web3-eth-contract.html#events) it all works same as it is for web3js.
Can you share the code snippets for the event subscription that is not working?
