### ISSUE TITLE
Cannot find eea_sendTransaction

### ISSUE THREAD

**Issue by damesca** [ConsenSys/web3js-quorum#49]
Hello,

I'm trying to use this library to send private transactions to Besu, but using EthSigner. However, I cannot find a method to send an "eea_sendTransaction" request.
Isn't it supported?

Thanks in advance

**Comment by macfarla** [comment]
Have a look at https://consensys.github.io/web3js-quorum/latest/tutorial-Migrate%20from%20web3js-eea.html - think you need to use `web3.priv.generateAndSendRawTransaction`
